version: "3.7"
services:
  db:
    image: percona:5.7
    container_name: db
    restart: always
    volumes:
       - ./logs/db:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go
    ports:  
      - "3307:3308"
    